# Generated by Django 4.2.6 on 2023-11-25 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational_modules', '0002_alter_modules_id_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='id_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='id_users', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
