# Generated by Django 4.2.6 on 2023-11-25 12:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('moderator', 'moderator'), ('teacher', 'teacher'), ('student', 'student')], max_length=23, null=True, verbose_name='роль пользователя'),
        ),
    ]
    