# Generated by Django 4.2.6 on 2023-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='educational-modules/students/photo', verbose_name='фото студента')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='учится')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
    ]
    