# Generated by Django 4.2.6 on 2023-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0003_alter_modules_id_users'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_modules.modules', verbose_name='образовательный модуль'),
        ),
    ]
    